// <referance types="cypress" />
describe("Acknoledger",function(){

    it("Visit url",function(){
        cy.visit("https://app.acknoledger.com/login")
        
    });
    it("login and logout",function(){
        cy.get('input[name="email"]').type('Acknoledger@dispostable.com',{force:true});
        cy.get('.input-wrap > .form-control').type('Sunil123$',{force:true});
        cy.get('.forgot > .btn-common').click({force:true});
        cy.get(':nth-child(3) > .m-0').click({force:true});

    });
    it('Forgot password',function() {
        cy.visit("https://app.acknoledger.com/login");
        cy.get('.duet-check > .text-decoration-none').click({force:true});
        cy.get('.form-control').type('Acknoledger@dispostable.com',{force:true});
        cy.get('.btn-secondary').click();// disabled due to OTP verification


    });
    it('Single upload',function() {
        cy.visit("https://app.acknoledger.com/login")
        cy.get('input[name="email"]').type('acknoledger@dispostable.com',{force:true})
        cy.get('.input-wrap > .form-control').type('Sunil123$',{force:true})
        cy.get('.forgot > .btn-common').click({force:true})
        cy.get('.mb-4.position-relative > .css-b62m3t-container > .css-1s2u09g-control > .css-1d8n9bt > .css-l4x4ky').click({force:true})
        cy.get('#react-select-2-input').type('tube')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.active > :nth-child(1) > :nth-child(2) > .form-control').type('100001',{force:true})
        cy.get(':nth-child(1) > :nth-child(3) > .form-control').type('https://images.pexels.com/photos/10980701/pexels-photo-10980701.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',{force:true})
        cy.get('.gx-2 > .position-relative > .css-b62m3t-container > .css-1s2u09g-control > .css-1d8n9bt > .css-l4x4ky').click({force:true})
        cy.get('#react-select-3-input').type('creator')
        cy.get('#react-select-3-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get('.gx-2 > .position-relative > .css-b62m3t-container > .css-1s2u09g-control > .css-1wy0on6 > :nth-child(1) > .css-8mmkcg > path').click({force:true})//1
        cy.get('#react-select-3-input').click({force:true})
        cy.get('#react-select-3-input').type('owner')
        cy.get('#react-select-3-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get('.gx-2 > .position-relative > .css-b62m3t-container > .css-1s2u09g-control > .css-1wy0on6 > :nth-child(1) > .css-8mmkcg > path').click({force:true})
        cy.get('#react-select-3-input').click({force:true})
        cy.get('#react-select-3-input').type('TokenUR')
        cy.get('#react-select-3-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get('.gx-2 > .position-relative > .css-b62m3t-container > .css-1s2u09g-control > .css-1wy0on6 > :nth-child(1) > .css-8mmkcg > path').click({force:true})
        cy.get('#react-select-3-input').click({force:true})
        cy.get('#react-select-3-input').type('transaction')
        cy.get('#react-select-3-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get('.gx-2 > .position-relative > .css-b62m3t-container > .css-1s2u09g-control > .css-1wy0on6 > :nth-child(1) > .css-8mmkcg > path').click({force:true})
        cy.get('#react-select-3-input').click({force:true})
        cy.get('#react-select-3-input').type('price')
        cy.get('#react-select-3-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get('.gx-2 > .position-relative > .css-b62m3t-container > .css-1s2u09g-control > .css-1wy0on6 > :nth-child(1) > .css-8mmkcg > path').click({force:true})
        cy.get('#react-select-3-input').click({force:true})
        cy.get('#react-select-3-input').type('token')
        cy.get('#react-select-3-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get('.gx-2 > .position-relative > .css-b62m3t-container > .css-1s2u09g-control > .css-1wy0on6 > :nth-child(1) > .css-8mmkcg > path').click({force:true})
        cy.get('#react-select-3-input').click({force:true})
        cy.get('#react-select-3-input').type('title')
        cy.get('#react-select-3-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get('.gx-2 > .position-relative > .css-b62m3t-container > .css-1s2u09g-control > .css-1wy0on6 > :nth-child(1) > .css-8mmkcg > path').click({force:true})
        cy.get('#react-select-3-input').click({force:true})
        cy.get('#react-select-3-input').type('description')
        cy.get('#react-select-3-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get('.gx-2 > .position-relative > .css-b62m3t-container > .css-1s2u09g-control > .css-1wy0on6 > :nth-child(1) > .css-8mmkcg > path').click({force:true})
        cy.get('#react-select-3-input').click({force:true})
        cy.get('#react-select-3-input').type('meta')
        cy.get('#react-select-3-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get('.gx-2 > .position-relative > .css-b62m3t-container > .css-1s2u09g-control > .css-1wy0on6 > :nth-child(1) > .css-8mmkcg > path').click({force:true})
        cy.get('#react-select-3-input').click({force:true})
        cy.get('#react-select-3-input').type('prop')
        cy.get('#react-select-3-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get('.gx-2 > .position-relative > .css-b62m3t-container > .css-1s2u09g-control > .css-1wy0on6 > :nth-child(1) > .css-8mmkcg > path').click({force:true})
        cy.get('#react-select-3-input').click({force:true})
        cy.get('#react-select-3-input').type('image')
        cy.get('#react-select-3-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get('.gx-2 > .position-relative > .css-b62m3t-container > .css-1s2u09g-control > .css-1wy0on6 > :nth-child(1) > .css-8mmkcg > path').click({force:true})
        cy.get('#react-select-3-input').click({force:true})
        cy.get('#react-select-3-input').type('location')
        cy.get('#react-select-3-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get('.gx-2 > .position-relative > .css-b62m3t-container > .css-1s2u09g-control > .css-1wy0on6 > :nth-child(1) > .css-8mmkcg > path').click({force:true})
        cy.get('#react-select-3-input').click({force:true})
        cy.get('#react-select-3-input').type('token name')
        cy.get('#react-select-3-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get('.gx-2 > .position-relative > .css-b62m3t-container > .css-1s2u09g-control > .css-1wy0on6 > :nth-child(1) > .css-8mmkcg > path').click({force:true})
        cy.get(':nth-child(4) > .btn-secondary').click({force:true})
    
    
    });
    it('Nft edit', function() {
    cy.visit("https://app.acknoledger.com/login")
        cy.get('input[name="email"]').type('acknoledger@dispostable.com',{force:true})
        cy.get('.input-wrap > .form-control').type('Sunil123$',{force:true})
        cy.get('.forgot > .btn-common').click({force:true})
        cy.get('.navbar-brand > img').click({force:true})
        cy.get('[src="https://images.pexels.com/photos/10980701/pexels-photo-10980701.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"]').click({force:true})
        //need to change the above image link
        cy.get('.active > .row > .overflow-hidden > .p-0.card > .pt-3 > .icon-actions > :nth-child(1)').click({force:true})
        cy.get('#react-select-2-input').type('creator')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('2',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})//1
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('owner')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('TokenUR')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('2',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('transaction')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('2',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('price')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('token')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('title')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('description')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('meta')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('prop')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('image')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('location')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('2',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('token name')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('2',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('.justify-content-start > :nth-child(1)').click({force:true})
});
    it('Nft delete', function() {
    cy.visit("https://app.acknoledger.com/login")
        cy.get('input[name="email"]').type('acknoledger@dispostable.com',{force:true})
        cy.get('.input-wrap > .form-control').type('Sunil123$',{force:true})
        cy.get('.forgot > .btn-common').click({force:true})
        cy.get('.navbar-brand > img').click({force:true})
        cy.get('[src="https://images.pexels.com/photos/10980701/pexels-photo-10980701.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"]').click({force:true})    
        //need to change the above image link
        cy.get('.active > .row > .overflow-hidden > .p-0.card > .pt-3 > .icon-actions > :nth-child(2) > svg').click({force:true})
});
});




        


   