it('Nft edit', function() {
    cy.visit("https://app.acknoledger.com/login")
        cy.get('input[name="email"]').type('acknoledger@dispostable.com',{force:true})
        cy.get('.input-wrap > .form-control').type('Sunil123$',{force:true})
        cy.get('.forgot > .btn-common').click({force:true})
        cy.get('.navbar-brand > img').click({force:true})
        cy.get('[src="https://images.pexels.com/photos/10980701/pexels-photo-10980701.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"]').click({force:true})
        cy.get('.active > .row > .overflow-hidden > .p-0.card > .pt-3 > .icon-actions > :nth-child(1)').click({force:true})
        cy.get('#react-select-2-input').type('creator')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('2',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})//1
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('owner')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('TokenUR')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('2',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('transaction')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('2',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('price')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('token')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('title')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('description')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('meta')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('prop')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('image')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('1',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('location')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('2',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('#react-select-2-input').click({force:true})
        cy.get('#react-select-2-input').type('token name')
        cy.get('#react-select-2-input').type('{enter}')
        cy.get('.col-lg-6 > .form-control').type('2',{force:true})
        cy.get('.form-control > .bi').click({force:true})
        cy.get(':nth-child(1) > .css-8mmkcg').click({force:true})
        cy.get('.justify-content-start > :nth-child(1)').click({force:true})
})    
